allowBuilds:
  blake-hash: true
  bufferutil: true
  esbuild: true
  protobufjs: true
  secp256k1: true
  sharp: true
  simple-git-hooks: false
  tiny-secp256k1: true
  unrs-resolver: true
  usb: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - sta-sdk@0.1.0
