import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    // `src/config.ts` validates the public Stellar configuration at import
    // time and throws when it is incomplete, so any test that transitively
    // imports it needs a valid set. These mirror `.env.example`.
    env: {
      NEXT_PUBLIC_STELLAR_RPC_URL: "https://soroban-testnet.stellar.org",
      NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015",
      NEXT_PUBLIC_STELLAR_EXPLORER_URL: "https://stellar.expert/explorer/testnet",
      NEXT_PUBLIC_SMART_ACCOUNT_ID:
        "CD6GY4UUTNPW4TUV7LDL5SELN4BBHJG4KDDT3W6G23DY6XCGM75MULMQ",
      NEXT_PUBLIC_POLICY_ENGINE_ID:
        "CCOP7NRMST5K6TL7FBDMX25LDEPW3DSFBOGBIKVFIDNAAZY7GBMVP3M4",
      NEXT_PUBLIC_INTENT_REGISTRY_ID:
        "CAFIATSIZQSBILZJWVT4PVDXPVITJHLP6LPAVKDRHCA7I7XPZSLTRPUS",
      NEXT_PUBLIC_RECOVERY_MANAGER_ID:
        "CCHC4YKVYS3CAZUOUYWYTEMQ6TZDW75WB2BGENUC2CDWDX5RH7NMKZWU",
      NEXT_PUBLIC_TRANSFER_ADAPTER_ID:
        "CBRYGIR3ORDW5LE6J7AVPSKRNTMRUYHD6FVPHQMJGPQLQ5FQUZ2U6GFH",
      NEXT_PUBLIC_SPLIT_ADAPTER_ID:
        "CBQA7UI7QN6RN4IZT7WPDHWTK2OO7J4FH2KMCVJGKMKVFGDURD63UQ7U",
      NEXT_PUBLIC_STA_ASSET_CONTRACT_ID:
        "CCOUVA654JH2V6B7LNTKHJP5DF3QA553RS2IIWXSGPDFH2N3QILIVU5L",
      NEXT_PUBLIC_TEST_RECIPIENT:
        "GAK3XILRBYBMBOCZMSLL2CLR6WPQLEIOC6ZCYYPTE4OIAX3PCFFO2YMU",
      NEXT_PUBLIC_ACCOUNT_FACTORY_ID:
        "CAQQTRRYNXIQGFVNCTMTBJDXW3PN7O44KPT7GWCCE4FRKTOHDBCWGUZO",
      NEXT_PUBLIC_RELAYER_EXECUTOR_ADDRESS:
        "GBFOESUTANPJZVQUZVKC5YCS4FB6AE5SX2R3JEDRK5JHKR22JXV4VNIV",
    },
  },
});
